### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by CartoonProgrammers**

### CODE REVIEW

**Comment by namishkhanna** [comment]
Place Code in HTML Folder.

**Comment by CartoonProgrammers** [comment]
But there is no html folder you are only having right to create one

**Comment by CartoonProgrammers** [comment]
Pls create one html folder

**Comment by namishkhanna** [comment]
You have to just add "HTML/index.html" in your file name, then it will automatically create HTML Folder.

**Comment by CartoonProgrammers** [comment]
Ok thq

**Comment by CartoonProgrammers** [comment]
Hi I did it now can you accept if you accept then I will get all my 4
projects done

**Pull request closed without merging**
